---
 - src: ./jenkins2.tar
 - dest: /root/dev/
 - imageloadname: jenkins/jenkins:latest
 - loadpath: /root/dev/jenkins2.tar
 - containername: jenkins
 - containerimage: jenkins/jenkins:latest
 - portnum: "8585:8080"

