---
- name: Archive build image
  hosts: all
  connection: local
  vars_files:
     - Archive_vars.yml
  tasks:
    - name: Archive image localy
      docker_image:
        name: "{{ image }}"
        archive_path: "{{ archive }}"
        source: local
- name: Deploy container
  hosts: all
  vars_files:
     - Deploy_vars.yml
  tasks:
    - name: cpoy image to dev
      copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
    - name: load image
      docker_image:
        name: "{{ imageloadname }}"
        load_path: "{{ loadpath }}"
        source: load
    - name: Start container
      docker_container:
        name: "{{ containername }}"
        image: "{{ containerimage }}"
        ports:
          - "{{ portnum }}"
        state: started
    - name: Remove dev directory
      file:
        path: "{{ dir }}"
        state: absent
